name: DermaShielder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0
  flutter_native_splash: ^2.4.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  file_picker: ^10.1.2
  image_picker: ^1.0.4
  provider: ^6.1.5
  chat_bubbles: ^1.3.2
  implicitly_animated_reorderable_list: ^0.4.1
  flutter_gemini: ^3.0.0
  tflite_flutter: ^0.11.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/DS_logo.jpeg
    - lib/assets/images/google_logo.png
    - lib/assets/images/logo_transparent.png
    - lib/assets/images/github_logo.png
    - lib/assets/images/default_profile.jpg
    - lib/models/resnet50_model.tflite


